package priv.kcl.bugcatisland.autoworkrobot.view;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class Viewer_ {
    private JPanel workerLayer;
    private JPanel receiverLayer;
    private JPanel gamblerLayer;
    private JPanel logLayer;
    private JPanel operationLayer;
    private JPanel rootLayer;
    private JButton btnStartRobot;
    private JButton btnStopRobot;
    private JTextArea txtareaLogMessage;
    private JCheckBox chkboxEnableReceiver;
    private JSpinner spinner;

    private final ViewModel viewModel;

    private final JFrame frame;

    public Viewer_(ViewModel viewModel) {
        this.viewModel = viewModel;

        frame = new JFrame();

        initView(frame);
        initFramePresentation(frame);

//        btnStartRobot.addActionListener(viewModel::buttonStartRobot_ActionListener);
//        btnStopRobot.addActionListener(viewModel::buttonStopRobot_ActionListener);
    }

    private void initView(JFrame frame) {
        frame.setContentPane($$$getRootComponent$$$());
    }

    private void initFramePresentation(JFrame frame) {
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setPreferredSize(new Dimension(500, 500));
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootLayer = new JPanel();
        rootLayer.setLayout(new GridBagLayout());
        workerLayer = new JPanel();
        workerLayer.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.weighty = 0.3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        rootLayer.add(workerLayer, gbc);
        workerLayer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-7632753)), "Worker", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        receiverLayer = new JPanel();
        receiverLayer.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.weighty = 0.3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        rootLayer.add(receiverLayer, gbc);
        receiverLayer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-7632753)), "Daily Receiver", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        chkboxEnableReceiver = new JCheckBox();
        chkboxEnableReceiver.setText("Enable Daily Receiver");
        chkboxEnableReceiver.setVerticalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        receiverLayer.add(chkboxEnableReceiver, gbc);
        final JLabel label1 = new JLabel();
        label1.setAlignmentY(0.5f);
        label1.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.weighty = 1.0;
        receiverLayer.add(label1, gbc);
        spinner = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        receiverLayer.add(spinner, gbc);
        gamblerLayer = new JPanel();
        gamblerLayer.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        rootLayer.add(gamblerLayer, gbc);
        gamblerLayer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-7632753)), "Gambler", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        logLayer = new JPanel();
        logLayer.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.6;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        rootLayer.add(logLayer, gbc);
        logLayer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-7632753)), "Log", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        txtareaLogMessage = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        logLayer.add(txtareaLogMessage, gbc);
        operationLayer = new JPanel();
        operationLayer.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 0.05;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(3, 3, 3, 3);
        rootLayer.add(operationLayer, gbc);
        btnStartRobot = new JButton();
        btnStartRobot.setText("Start Robot");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(8, 8, 8, 8);
        operationLayer.add(btnStartRobot, gbc);
        btnStopRobot = new JButton();
        btnStopRobot.setText("Stop Robot");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(8, 8, 8, 8);
        operationLayer.add(btnStopRobot, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootLayer;
    }

    public static void main(String[] args) {
//        new Viewer(new ViewModel(new Model()));
    }

}
